export enum UsersPermissionsEnum {
  USER_CREATE = 'USER CAN CREATE',
  USER_READ = 'USER CAN READ',
  USER_EDIT = 'USER CAN EDIT',
  USER_DELETE = 'USER CAN DELETE',
  DIARY_CREATE = 'DIARY CAN CREATE',
  DIARY_READ = 'DIARY CAN READ',
  DIARY_EDIT = 'DIARY CAN EDIT',
  DIARY_DELETE = 'DIARY CAN DELETE',
}
